# Generated by Django 6.1 on 2026-09-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coolieprofile',
            options={'ordering': ['-rating', '-experience_years']},
        ),
    ]
