# Generated by Django 6.1 on 2026-09-02 07:08

import django.db.models.deletion
import django.utils.timezone
import lost_found.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(default=lost_found.models.generate_lost_found_id, max_length=30, unique=True)),
                ('report_type', models.CharField(choices=[('LOST', '❌ I Lost Something'), ('FOUND', '✅ I Found Something')], default='LOST', max_length=10)),
                ('item_name', models.CharField(help_text='e.g. Black Lenovo ThinkPad Laptop Bag', max_length=150)),
                ('category', models.CharField(choices=[('ELECTRONICS', '📱 Mobile / Laptop / Electronics'), ('LUGGAGE_BAG', '🧳 Luggage / Backpack / Handbag'), ('WALLET_DOCS', '💳 Wallet / ID Cards / Documents'), ('VALUABLES', '💍 Jewelry / Watch / Valuables'), ('CLOTHING', '🧥 Jackets / Clothing / Accessories'), ('KEYS', '🔑 Keys / Essentials'), ('OTHER', '📦 Other Items')], default='LUGGAGE_BAG', max_length=30)),
                ('description', models.TextField(help_text='Detailed physical description, stickers, brand, color, unique marks')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_found/')),
                ('image_url', models.CharField(blank=True, help_text='Fallback image URL for demo', max_length=500)),
                ('coach_number', models.CharField(blank=True, help_text='e.g. A1 Berth 23', max_length=30)),
                ('incident_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('REPORTED', 'Report Submitted'), ('UNDER_VERIFICATION', 'Under Verification by Station Master'), ('MATCHED', 'Potential Match Found'), ('CLAIMED', 'Claimed by Owner'), ('RESOLVED', 'Resolved & Handed Over'), ('CLOSED', 'Closed / Unclaimed')], default='REPORTED', max_length=30)),
                ('storage_location', models.CharField(blank=True, help_text='e.g. Station Master Office Locker B', max_length=200)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_reports', to='stations.platform')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_reports', to='stations.station')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
