# Generated by Django 6.1 on 2026-09-02 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Station Full Name (e.g. New Jalpaiguri Junction)', max_length=150)),
                ('code', models.CharField(help_text='Station Code (e.g. NJP)', max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('number_of_platforms', models.PositiveIntegerField(default=5)),
                ('latitude', models.DecimalField(decimal_places=6, default=26.6853, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=88.4418, max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stations/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, help_text='e.g. Main lines, Rajdhani/Vande Bharat berth', max_length=200)),
                ('has_lift', models.BooleanField(default=True)),
                ('has_escalator', models.BooleanField(default=True)),
                ('has_wheelchair_ramp', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='stations.station')),
            ],
            options={
                'ordering': ['station', 'number'],
                'unique_together': {('station', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('WASHROOM', '🚻 Washroom / Restroom'), ('DRINKING_WATER', '💧 Clean Drinking Water'), ('LIFT', '🛗 Passenger Lift / Elevator'), ('ESCALATOR', '🚶 Escalator'), ('FOOD', '🍴 Food Court & Refreshments'), ('WAITING_ROOM', '🪑 AC & General Waiting Room'), ('PARKING', '🚗 Station Parking Area'), ('MEDICAL', '🏥 Emergency Medical Room'), ('HELP_DESK', 'ℹ️ Sahayata / Help Desk'), ('CLOAK_ROOM', '🛅 Cloak Room & Luggage Locker'), ('WHEELCHAIR_POINT', '♿ Wheelchair Pick-up Hub')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('location_description', models.CharField(help_text='e.g. Near FOB 1, Platform 1 Center', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, default=26.6853, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=88.4418, max_digits=9)),
                ('is_operational', models.BooleanField(default=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('icon', models.CharField(default='fa-info-circle', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='stations.platform')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='stations.station')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['station', 'facility_type'],
            },
        ),
    ]
