# Generated by Django 6.1 on 2026-09-02 07:08

import assistance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default=assistance.models.generate_assistance_id, max_length=30, unique=True)),
                ('passenger_name', models.CharField(max_length=150)),
                ('passenger_phone', models.CharField(max_length=20)),
                ('coach_number', models.CharField(blank=True, help_text='e.g. S3, B4, General', max_length=30)),
                ('train_number', models.CharField(blank=True, help_text='e.g. 12345 Saraighat Express', max_length=50)),
                ('assistance_type', models.CharField(choices=[('WHEELCHAIR', '♿ Wheelchair Assistance'), ('SENIOR_CITIZEN', '👴 Senior Citizen Assistance'), ('FAMILY_CHILD', '👨\u200d👩\u200d👧 Family & Child Care Assistance'), ('LUGGAGE', '🧳 Luggage Transit Help'), ('MEDICAL_EMERGENCY', '🏥 Medical First Aid Assistance'), ('GENERAL_HELP', '🙋 General Station Help & Guidance')], default='WHEELCHAIR', max_length=30)),
                ('description', models.TextField(help_text='Provide any specific details (e.g. need ramp access, unable to climb stairs)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Staff Assigned'), ('IN_PROGRESS', 'Assistance In Progress'), ('RESOLVED', 'Completed / Resolved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('assigned_staff_name', models.CharField(blank=True, max_length=150)),
                ('assigned_staff_phone', models.CharField(blank=True, max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_requests', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_requests', to='stations.platform')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to='stations.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
