# Generated by Django 6.1 on 2026-09-02 07:08

import complaints.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(default=complaints.models.generate_complaint_id, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('CLEANLINESS', '🧹 Station / Platform Cleanliness Issue'), ('COOLIE_OVERCHARGING', '🧳 Coolie Overcharging / Misbehavior'), ('DEFECTIVE_FACILITY', '🛗 Broken Lift / Escalator / Washroom'), ('STAFF_BEHAVIOR', '👮 Station Staff / Porter Misconduct'), ('SAFETY_SECURITY', '🛡️ Safety & Security Concern'), ('DRINKING_WATER', '💧 Water Dispenser Empty / Dirty'), ('FOOD_QUALITY', '🍴 Overpricing / Poor Food Hygiene'), ('OTHER', '📢 Other Railway Grievances')], default='CLEANLINESS', max_length=30)),
                ('description', models.TextField(help_text='Explain the problem in detail with specific locations or porter badge numbers if applicable')),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', '🚨 Urgent / Emergency')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New Grievance Submitted'), ('ASSIGNED', 'Assigned to Railway Officer'), ('IN_PROGRESS', 'Investigation in Progress'), ('RESOLVED', 'Issue Resolved'), ('REJECTED', 'Dismissed / Inapplicable')], default='NEW', max_length=20)),
                ('assigned_officer', models.CharField(blank=True, max_length=150)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='stations.platform')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='stations.station')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
