# Generated by Django 6.1 on 2026-09-02 07:08

import bookings.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default=bookings.models.generate_booking_id, max_length=30, unique=True)),
                ('journey_type', models.CharField(choices=[('ARRIVAL', 'Train Arrival (De-boarding)'), ('DEPARTURE', 'Train Departure (Boarding)')], default='ARRIVAL', max_length=20)),
                ('train_number', models.CharField(blank=True, help_text='e.g. 12042 New Jalpaiguri Shatabdi', max_length=20)),
                ('train_name', models.CharField(blank=True, max_length=100)),
                ('coach_number', models.CharField(blank=True, help_text='e.g. B2, C1, S4', max_length=20)),
                ('seat_number', models.CharField(blank=True, help_text='e.g. 45, 52', max_length=20)),
                ('luggage_type', models.CharField(choices=[('TROLLEY', 'Trolley Bags / Suitcases'), ('HEAVY_BAGS', 'Duffel / Heavy Rucksacks'), ('BOXES', 'Carton Boxes / Packages'), ('COMBINED', 'Mixed / Multiple Luggage')], default='TROLLEY', max_length=30)),
                ('number_of_bags', models.PositiveIntegerField(default=2)),
                ('approx_weight_kg', models.PositiveIntegerField(default=25)),
                ('special_notes', models.TextField(blank=True, help_text='e.g. Elderly passenger travelling, need wheelchair along with coolie')),
                ('meeting_point', models.CharField(blank=True, default='Platform 1 Main Entrance', max_length=200)),
                ('scheduled_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('base_fare', models.DecimalField(decimal_places=2, default=120.0, max_digits=8)),
                ('extra_bag_fare', models.DecimalField(decimal_places=2, default=60.0, max_digits=8)),
                ('total_fare', models.DecimalField(decimal_places=2, default=180.0, max_digits=8)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested (Waiting for Coolie)'), ('ACCEPTED', 'Accepted by Coolie'), ('REJECTED', 'Rejected'), ('SERVICE_STARTED', 'Service Started (Coolie Reached)'), ('COMPLETED', 'Service Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('coolie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='accounts.coolieprofile')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='stations.platform')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stations.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
